name: Python CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10" ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install pycodestyle pydocstyle pylint pyflakes flake8
      - name: Linting with pycodestyle
        run: find . -name \*.py -exec pycodestyle {} +
      - name: Linting with pydocstyle
        run: find . -name \*.py -exec pydocstyle {} +
      - name: Linting with pylint
        run: find . -name \*.py -exec pylint --disable=F0401,W0613,C0415,W0703 {} +
      - name: Linting with pyflakes
        run: find . -name \*.py -exec pyflakes {} +
      - name: Linting with flake8
        run: find . -name \*.py -exec flake8 {} +

